// SPDX-FileCopyrightText: 2026 Paweł Krzywdziński and Contributors
// SPDX-License-Identifier: Apache-2.0

/// Every family of cases, one for each contract the library declares: the controls, the parts of an application's
/// structure, then the tiers.
/// Design: docs/design/host/conformance.md#one-family-per-contract
@_spi(Host) public enum Families {
    /// Every family, in the dictionary's order.
    public static let all: [any ConformanceFamily.Type] = [
        ActivityIndicatorTests.self,
        ButtonTests.self,
        CanvasTests.self,
        CheckBoxTests.self,
        ColorPickerTests.self,
        DatePickerTests.self,
        EllipseTests.self,
        GridTests.self,
        HStackTests.self,
        ImageTests.self,
        TextTests.self,
        LineTests.self,
        MapTests.self,
        PathTests.self,
        PickerTests.self,
        PolygonTests.self,
        PolylineTests.self,
        PositionIndicatorTests.self,
        ProgressBarTests.self,
        RadioButtonTests.self,
        RectangleTests.self,
        ScrollViewTests.self,
        ListTests.self,
        SearchFieldTests.self,
        SliderTests.self,
        StepperTests.self,
        SwitchTests.self,
        TextEditorTests.self,
        TextFieldTests.self,
        TimePickerTests.self,
        TitleBarTests.self,
        VStackTests.self,
        WebViewTests.self,
        ZStackTests.self,
        ApplicationTests.self,
        ContentTests.self,
        ContextMenuTests.self,
        LeadingContentTests.self,
        MenuTests.self,
        MenuBarTests.self,
        MenuItemTests.self,
        MenuSeparatorTests.self,
        ModalStackTests.self,
        NavigationStackTests.self,
        OverlayTests.self,
        PageTests.self,
        PinTests.self,
        SceneTests.self,
        SpanTests.self,
        SpansTests.self,
        NavigationSplitViewTests.self,
        TabViewTests.self,
        TitleViewTests.self,
        ToolbarItemTests.self,
        ToolbarItemsTests.self,
        TrailingContentTests.self,
        WindowTests.self,
        PropertyContainerTests.self,
        VisualElementTests.self,
        ViewTests.self,
        LayoutTests.self,
        StackBaseTests.self,
        InputViewTests.self,
        ShapeTests.self,
        TextElementTests.self,
        TextStyleElementTests.self,
        FontElementTests.self,
        TextAlignmentElementTests.self,
        LineHeightElementTests.self,
        DecorableTextElementTests.self,
        PaddingElementTests.self,
        BorderElementTests.self,
        ImageElementTests.self,
        TintElementTests.self,
        BarElementTests.self,
        MenuItemElementTests.self,
        PageElementTests.self,
    ]
}
